Repository matthiasgomolka/sdcLog, pull requests merged in 2020-03, with the labels that each got.

#5 print method for sdc_model
  NAMESPACE
  R/print_methods.R
  R/sdc_model.R
  R/utils.R
  sdcLog.Rproj
  tests/testthat/test-sdc_descriptives.R
Labels: enhancement

#12 Problem status message extreme
  R/sdc_extreme.R
  R/status_messages.R
  tests/testthat/test-sdc_extreme.R
Labels: bug

#13 correct message arguments if by is unquoted
  R/sdc_descriptives.R
  R/status_messages.R
Labels: bug

#15 Correct handling of by in sdc_extreme()
  DESCRIPTION
  R/sdc_extreme.R
Labels: bug

#14 Tests sdc extreme
  NAMESPACE
  R/sdc_extreme.R
  man/sdc_extreme.Rd
  tests/testthat/test-sdc_extreme.R
Labels: tests

#22 sdc_model output at sdc.info_level 2
  .Rbuildignore
  .gitignore
  DESCRIPTION
  R/sdc_model.R
  vignettes/.gitignore
  vignettes/options.Rmd
  vignettes/sdcLog.Rmd
Labels: bug

#23 Vignette for options
  Meta/vignette.rds
  doc/options.R
  doc/options.Rmd
  doc/options.html
  doc/sdcLog.R
  doc/sdcLog.Rmd
  doc/sdcLog.html
  vignettes/options.R
  vignettes/options.Rmd
Labels: documentation
